/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_apkdiffpatch_ApkDiffPatchUtil */

#ifndef _Included_com_demo_apkdiffpatch_ApkDiffPatchUtil
#define _Included_com_demo_apkdiffpatch_ApkDiffPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_apkdiffpatch_ApkDiffPatchUtil
 * Method:    zipPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
extern "C"
JNIEXPORT jint JNICALL Java_com_demo_apkdiffpatch_ApkDiffPatchUtil_zipPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
